In [87]:
import os
import h5py
import glob
import math

import numpy      as np
import tensorflow as tf

from sklearn.preprocessing import MinMaxScaler

In [88]:
%matplotlib inline

In [89]:
#TEST Chamfer loss
data_in = np.array([[[-1, 0, 1.5], [-0.5, 0, 2]], [[0, 10, 0], [1, 9, 2]]])
print(data_in.shape)
print(data_in)

data_out = data_in[:,:,0]
print(data_out.shape)
print(data_out)

data_out = tf.expand_dims(data_out, 1)
print(data_out.shape)
print(data_out)

(2, 2, 3)
[[[-1.   0.   1.5]
  [-0.5  0.   2. ]]

 [[ 0.  10.   0. ]
  [ 1.   9.   2. ]]]
(2, 2)
[[-1.  -0.5]
 [ 0.   1. ]]
(2, 1, 2)
tf.Tensor(
[[[-1.  -0.5]]

 [[ 0.   1. ]]], shape=(2, 1, 2), dtype=float64)


In [90]:
#TEST Chamfer loss
data_in = np.array([[-1, 0, 1.5], [0.5, 1, 2.5], [0, 10, 0], [1, 9, 2]])
data_out = np.array([[0., 1, 2], [1, -2, 3], [3, 0, -4]])

print("data_in.shape", data_in.shape)
print("data_out.shape", data_out.shape)

data_in = tf.expand_dims(data_in, 1)
data_out = tf.expand_dims(data_out, 0)

print("data_in", data_in)
print("data_out", data_out)

sq = tf.math.squared_difference(data_in, data_out)
print("sq", sq)

sum = tf.math.reduce_sum(sq, -1)
print("sum", sum)

print(tf.math.reduce_min(sum, 0))
print(tf.math.reduce_min(sum,1))

data_in.shape (4, 3)
data_out.shape (3, 3)
data_in tf.Tensor(
[[[-1.   0.   1.5]]

 [[ 0.5  1.   2.5]]

 [[ 0.  10.   0. ]]

 [[ 1.   9.   2. ]]], shape=(4, 1, 3), dtype=float64)
data_out tf.Tensor(
[[[ 0.  1.  2.]
  [ 1. -2.  3.]
  [ 3.  0. -4.]]], shape=(1, 3, 3), dtype=float64)
sq tf.Tensor(
[[[  1.     1.     0.25]
  [  4.     4.     2.25]
  [ 16.     0.    30.25]]

 [[  0.25   0.     0.25]
  [  0.25   9.     0.25]
  [  6.25   1.    42.25]]

 [[  0.    81.     4.  ]
  [  1.   144.     9.  ]
  [  9.   100.    16.  ]]

 [[  1.    64.     0.  ]
  [  0.   121.     1.  ]
  [  4.    81.    36.  ]]], shape=(4, 3, 3), dtype=float64)
sum tf.Tensor(
[[  2.25  10.25  46.25]
 [  0.5    9.5   49.5 ]
 [ 85.   154.   125.  ]
 [ 65.   122.   121.  ]], shape=(4, 3), dtype=float64)
tf.Tensor([ 0.5   9.5  46.25], shape=(3,), dtype=float64)
tf.Tensor([ 2.25  0.5  85.   65.  ], shape=(4,), dtype=float64)


In [91]:
#TEST Chamfer loss
data_in = np.array([-1, -0.5, 0, 1])
data_out = np.array([0., 1, 3, -2])

print("data_in.shape", data_in.shape)
print("data_out.shape", data_out.shape)

data_in = tf.expand_dims(data_in, 1)
data_out = tf.expand_dims(data_out, 0)

print("data_in", data_in)
print("data_out", data_out)

sq = tf.math.squared_difference(data_in, data_out)
print("sq", sq)

sum = tf.math.reduce_sum(sq, -1)
print("sum", sum)

print(tf.math.reduce_min(sum, 0))
#print(tf.math.reduce_min(sum,1))

data_in.shape (4,)
data_out.shape (4,)
data_in tf.Tensor(
[[-1. ]
 [-0.5]
 [ 0. ]
 [ 1. ]], shape=(4, 1), dtype=float64)
data_out tf.Tensor([[ 0.  1.  3. -2.]], shape=(1, 4), dtype=float64)
sq tf.Tensor(
[[ 1.    4.   16.    1.  ]
 [ 0.25  2.25 12.25  2.25]
 [ 0.    1.    9.    4.  ]
 [ 1.    0.    4.    9.  ]], shape=(4, 4), dtype=float64)
sum tf.Tensor([22. 17. 14. 14.], shape=(4,), dtype=float64)
tf.Tensor(14.0, shape=(), dtype=float64)


In [92]:
#TEST zero padding

data = np.array([[-1, 2], [-0.5, 6], [0, 10], [1, 18]])
print("data.shape", data.shape)
print("data", data)

data_1 = np.zeros(shape=(4,3))
print("data_1", data_1)

data_1[:, 1:3] += data

print("data_1", data_1)

data.shape (4, 2)
data [[-1.   2. ]
 [-0.5  6. ]
 [ 0.  10. ]
 [ 1.  18. ]]
data_1 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
data_1 [[ 0.  -1.   2. ]
 [ 0.  -0.5  6. ]
 [ 0.   0.  10. ]
 [ 0.   1.  18. ]]


In [93]:
#TEST sum of elemets if data_1 elements are non-zero
data = np.array([[-1, 2], [-0.5, 6], [0, 10], [1, 18]])

data_1 = np.array([[0, 1], [1.5, 3], [2, 2], [2, 4]])

print("data.shape", data.shape)

print(data[np.nonzero(data_1)]+data_1[np.nonzero(data_1)])

data.shape (4, 2)
[ 3.  1.  9.  2. 12.  3. 22.]


In [94]:
#Test mse
from tensorflow.keras import backend as K

data = np.array([[[[-1, 2], [-0.5, 6], [0, 10], [1, 18]],
                  [[-1, 2], [-0.5, 6], [0, 10], [1, 18]]]])

data_1 = np.array([[[[-2, 1], [1.5, 3], [2, 2], [2, 4]],
                  [[-3, 2], [-2.5, 4], [5, 1], [3, 1]]]])

print("data.shape", data.shape)
print("data", data)

print("data_1.shape", data_1.shape)
print("data_1", data_1)

data_2 = data-data_1
print("data_2.shape", data_2.shape)
print("data_2", data_2)

data = K.square(data_2)
print("data.shape", data.shape)
print("data", data)

data.shape (1, 2, 4, 2)
data [[[[-1.   2. ]
   [-0.5  6. ]
   [ 0.  10. ]
   [ 1.  18. ]]

  [[-1.   2. ]
   [-0.5  6. ]
   [ 0.  10. ]
   [ 1.  18. ]]]]
data_1.shape (1, 2, 4, 2)
data_1 [[[[-2.   1. ]
   [ 1.5  3. ]
   [ 2.   2. ]
   [ 2.   4. ]]

  [[-3.   2. ]
   [-2.5  4. ]
   [ 5.   1. ]
   [ 3.   1. ]]]]
data_2.shape (1, 2, 4, 2)
data_2 [[[[ 1.  1.]
   [-2.  3.]
   [-2.  8.]
   [-1. 14.]]

  [[ 2.  0.]
   [ 2.  2.]
   [-5.  9.]
   [-2. 17.]]]]
data.shape (1, 2, 4, 2)
data tf.Tensor(
[[[[  1.   1.]
   [  4.   9.]
   [  4.  64.]
   [  1. 196.]]

  [[  4.   0.]
   [  4.   4.]
   [ 25.  81.]
   [  4. 289.]]]], shape=(1, 2, 4, 2), dtype=float64)


In [95]:
y_true = np.array([[[1,4,2,3], [9,2,1,5]], [[2,3,1,5], [1,3,4,2]]])
x_true = np.array([[0,2,0,5]])

print("1 ", y_true.shape)
print("1 ", y_true[0])
 
y_true = tf.reshape(y_true, shape=(2, 8))
print("2 ", y_true)
print("2 ", y_true[0])

idx_keep = tf.where(y_true[0]!=0)[:,-1]
print("3 ", idx_keep)

values_keep = tf.gather(y_true[0,:], idx_keep)
print("4 ", values_keep)

values_keep = tf.reshape(values_keep, shape=(values_keep.shape[0], 1))
print("5 ", values_keep)

expand_inputs = tf.expand_dims(values_keep, 1)
print("6 ", expand_inputs)

expand_outputs = tf.expand_dims(values_keep, 0)
print("7 ", expand_outputs)

distances = tf.math.reduce_sum(tf.math.squared_difference(expand_inputs, expand_outputs), -1)
print("8 ", distances)

min_dist_to_inputs = tf.math.reduce_min(distances, 0)
min_dist_to_outputs = tf.math.reduce_min(distances, 1)
print("9 ", min_dist_to_inputs)
print("10 ", min_dist_to_outputs)

print("11 ", tf.math.reduce_mean(min_dist_to_inputs, 0))
print("12 ", tf.math.reduce_mean(min_dist_to_outputs, 0))

1  (2, 2, 4)
1  [[1 4 2 3]
 [9 2 1 5]]
2  tf.Tensor(
[[1 4 2 3 9 2 1 5]
 [2 3 1 5 1 3 4 2]], shape=(2, 8), dtype=int64)
2  tf.Tensor([1 4 2 3 9 2 1 5], shape=(8,), dtype=int64)
3  tf.Tensor([0 1 2 3 4 5 6 7], shape=(8,), dtype=int64)
4  tf.Tensor([1 4 2 3 9 2 1 5], shape=(8,), dtype=int64)
5  tf.Tensor(
[[1]
 [4]
 [2]
 [3]
 [9]
 [2]
 [1]
 [5]], shape=(8, 1), dtype=int64)
6  tf.Tensor(
[[[1]]

 [[4]]

 [[2]]

 [[3]]

 [[9]]

 [[2]]

 [[1]]

 [[5]]], shape=(8, 1, 1), dtype=int64)
7  tf.Tensor(
[[[1]
  [4]
  [2]
  [3]
  [9]
  [2]
  [1]
  [5]]], shape=(1, 8, 1), dtype=int64)
8  tf.Tensor(
[[ 0  9  1  4 64  1  0 16]
 [ 9  0  4  1 25  4  9  1]
 [ 1  4  0  1 49  0  1  9]
 [ 4  1  1  0 36  1  4  4]
 [64 25 49 36  0 49 64 16]
 [ 1  4  0  1 49  0  1  9]
 [ 0  9  1  4 64  1  0 16]
 [16  1  9  4 16  9 16  0]], shape=(8, 8), dtype=int64)
9  tf.Tensor([0 0 0 0 0 0 0 0], shape=(8,), dtype=int64)
10  tf.Tensor([0 0 0 0 0 0 0 0], shape=(8,), dtype=int64)
11  tf.Tensor(0, shape=(), dtype=int64)
12  tf.T

In [114]:
#TEST AveragePooling2D and UpSampling2D

x = tf.constant([[[[1., 2., 3.]]]])
print("x", x)
avg_pool_2d = tf.keras.layers.UpSampling2D((2, 2))

x = avg_pool_2d(x)
print("x", x)

x = tf.reshape(x, [1, 1, 2, 6])
print("x", x)

x tf.Tensor([[[[1. 2. 3.]]]], shape=(1, 1, 1, 3), dtype=float32)
x tf.Tensor(
[[[[1. 2. 3.]
   [1. 2. 3.]]

  [[1. 2. 3.]
   [1. 2. 3.]]]], shape=(1, 2, 2, 3), dtype=float32)
x tf.Tensor(
[[[[1. 2. 3. 1. 2. 3.]
   [1. 2. 3. 1. 2. 3.]]]], shape=(1, 1, 2, 6), dtype=float32)


In [120]:
#TEST np.sum

data_1 = np.array([[[[-1, 2], [-0.5, 6], [0, 10]] , [[-0.5, 1], [-1.5, 2], [1, 4]] , 
                   [[-1, 2], [-1, 2], [0, 10]] , [[-1, 2], [-1.5, 2], [0, 10]]],
                  [[[-0.5, 1], [-0.5, 6], [-0.5, 1]] , [[-0.5, 1], [-0.5, 6], [-0.5, 1]] , 
                   [[-1, 2], [-1.5, 2], [0, 10]] , [[-1.5, 2], [1, 4], [0, 10]]]
                 ])
print("data_1.shape", data_1.shape)

data_2 = np.array([[[[-1, 2], [-0.5, 6], [0, 10]]]])
print("data_2.shape", data_2.shape)

print(K.mean(K.square(data_1), axis=[1,2,3]))
print(K.sum(K.square(data_1), axis=[1,2,3]))

print(K.mean(K.square(data_2), axis=[1,2,3]))
print(K.sum(K.square(data_2), axis=[1,2,3]))

#print((data1-data2) * (data1-data2))
#print(K.mean(K.square(data1-data2), axis = -1))
#print(K.sum(K.mean(K.square(data1-data2), axis = -1)))
#data1 = data1.sum(axis=2)
#print(data1)
#data1 = data1.sum(-1)
#print(data1.shape)
#print(data1)

data_1.shape (2, 4, 3, 2)
data_2.shape (1, 1, 3, 2)
tf.Tensor([16.125 13.   ], shape=(2,), dtype=float64)
tf.Tensor([387. 312.], shape=(2,), dtype=float64)
tf.Tensor([23.54166667], shape=(1,), dtype=float64)
tf.Tensor([141.25], shape=(1,), dtype=float64)


In [126]:
#TEST MinMaxScaler

data = np.array([[[1, 0.15], [0.5, 0.65], [0, 0.75], [0.35, 1]], [[1, 0.15], [0.5, 0.65], [0, 0.75], [0.35, 2]]])

print("data.shape", data.shape)
print("data", data)

data = data.reshape(-1, 1)

print("data.shape", data.shape)
print("data", data)

print("np.mean(data)", np.mean(data))
print("np.var(data)", np.var(data))

scaler = MinMaxScaler()
scaler.fit(data)
print("data_min_", scaler.data_min_)
print("data_max_", scaler.data_max_)

data = scaler.transform(data)
print("data.shape", data.shape)
print("data", data)

data = data.reshape(2, 4, 2)
print("data.shape", data.shape)
print("data", data)

print("np.mean(data)", np.mean(data))
print("np.var(data)", np.var(data))

data.shape (2, 4, 2)
data [[[1.   0.15]
  [0.5  0.65]
  [0.   0.75]
  [0.35 1.  ]]

 [[1.   0.15]
  [0.5  0.65]
  [0.   0.75]
  [0.35 2.  ]]]
data.shape (16, 1)
data [[1.  ]
 [0.15]
 [0.5 ]
 [0.65]
 [0.  ]
 [0.75]
 [0.35]
 [1.  ]
 [1.  ]
 [0.15]
 [0.5 ]
 [0.65]
 [0.  ]
 [0.75]
 [0.35]
 [2.  ]]
np.mean(data) 0.6125
np.var(data) 0.23484375
data_min_ [0.]
data_max_ [2.]
data.shape (16, 1)
data [[0.5  ]
 [0.075]
 [0.25 ]
 [0.325]
 [0.   ]
 [0.375]
 [0.175]
 [0.5  ]
 [0.5  ]
 [0.075]
 [0.25 ]
 [0.325]
 [0.   ]
 [0.375]
 [0.175]
 [1.   ]]
data.shape (2, 4, 2)
data [[[0.5   0.075]
  [0.25  0.325]
  [0.    0.375]
  [0.175 0.5  ]]

 [[0.5   0.075]
  [0.25  0.325]
  [0.    0.375]
  [0.175 1.   ]]]
np.mean(data) 0.30625
np.var(data) 0.0587109375


In [130]:
#TEST generator

def count(stop):
    i = 0
    print("i ", i, "stop ", stop)
    while i < stop:
        i += 1
        yield i

counter = tf.data.Dataset.from_generator(count, args=[25], output_types=tf.int32, output_shapes = (), )

for count_batch in counter.repeat().batch(2).take(3):
  print(count_batch.numpy())

i  0 stop  25
[1 2]
[3 4]
[5 6]


In [131]:
#TEST ECAL/HCAL binning 

import math

print(2.443*2/(1*0.01745))
print(math.pi)
for x in range(-145, -146):
    print(x, x * 1*0.01745)

280.0
3.141592653589793


In [136]:
#TEST log10

data = np.array([[[1, 0.15], [0.5, 0.65], [0, 0.75], [0.35, 1]], [[1, 0.15], [0.5, 0.65], [0, 0.75], [0.35, 1]]])

data = np.log10(data, out=np.zeros_like(data), where=(data!=0), dtype=np.float16)

print(data[np.nonzero(data)])

[-0.82373047 -0.30102539 -0.18713379 -0.12493896 -0.45581055 -0.82373047
 -0.30102539 -0.18713379 -0.12493896 -0.45581055]


In [137]:
#TEST log10
x = np.array([[1., 4.], [2., 3.]])
print("x", x)

x = np.log10(x, where=(x!=1), out=np.zeros_like(x), dtype=np.float16)
print("x", x)

x [[1. 4.]
 [2. 3.]]
x [[0.         0.60205078]
 [0.30102539 0.47705078]]
